{
    'name': 'hospital',
    'version': '15.0.1.0.0.',
    'summary': '',
    'category': 'Customization',
    'author': '',
    'website': '',
    'license': 'OPL-1',
    'depends': [],
    'data': [
        'security/ir.model.access.csv',
        'views/hr_hospital_menu.xml',
        'views/research_views.xml',
        'views/diagnosis_views.xml',
        'views/doctor_views.xml',
        'views/patient_views.xml',
        'views/sick_views.xml',
        'views/visit_to_doctor_views.xml',
        'views/contact_person_views.xml',
        'views/history_of_personal_doctor_views.xml',
        'wizard/doctor_multi_wizard_views.xml',
    ],
    'demo': [],
    'installable': True,
    'auto_install': False,
}
